### ISSUE TITLE
Add a (possibly open source) license

### ISSUE THREAD

**Issue by christian-heusel** [niels-beier/muesli_app#2]
Hey @niels-beier! 🥳 
Good job and thanks for creating an app for MUESLI! 📱

I think it would be great to license the published code appropriately, https://choosealicense.com/ could be a great start 😊
MUESLI itself uses the GPLv3 (see https://github.com/muesli-hd/muesli/blob/master/LICENSE) 

If you want we can discuss this further here, once agreed I could also create a PR for the chosen license. :)

**Comment by christian-heusel** [comment]
Choose a license also has a good page on why one should choose a license: https://choosealicense.com/no-permission/

**Comment by 0xshuzo** [comment]
Yeah, I did think about that when publishing, just didn't have the time to choose and add one.
I think GPLv3 would be the choice to go since the project or some of its content should be usable for others without anything of it getting closed source.

**Comment by christian-heusel** [comment]
Do you include the license or should I submit a PR?

**Comment by 0xshuzo** [comment]
I'll just add one. Thanks for helping!
Closing.
